version: '3'
services: 
    web:
        container_name: web
        image: server_eccomerce_test
        build: .
        command: node server.js
        ports: 
            - "3000:3000"
        volumes:
            - .:/usr/app
            - /usr/src/app/node_modules
        depends_on: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        build: .
        volumes:
          - ./data:/data/db
        ports:
          - "27017:27017"